GET http://localhost:3000/places?text=joao monlevade, loanda

###

@originId = yourOriginId
@destinationId = yourDestinationId

###

GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/674ef78bab1148ea9161c23b